# Generated by Django 5.2.1 on 2025-05-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='inputKeterangan',
            new_name='keterangan',
        ),
        migrations.RenameField(
            model_name='postdata',
            old_name='inputNama',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='postdata',
            old_name='choiceRuangan',
            new_name='ruangan',
        ),
        migrations.RenameField(
            model_name='postdata',
            old_name='inputSatker',
            new_name='satker',
        ),
        migrations.RemoveField(
            model_name='postdata',
            name='waktuPinjam',
        ),
    ]
