# Generated by Django 5.2.1 on 2025-05-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0002_rename_inputketerangan_postdata_keterangan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='nama',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
