# Generated by Django 5.2.1 on 2025-05-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0003_alter_postdata_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='nama',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
