# Generated by Django 5.2.1 on 2025-05-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0004_alter_postdata_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='ruangan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='satker',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
