# Generated by Django 5.2.1 on 2025-05-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0005_alter_postdata_ruangan_alter_postdata_satker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
