# Generated by Django 5.2.1 on 2025-05-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0006_alter_postdata_keterangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaRuangan', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaUser', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
