# Generated by Django 5.2.1 on 2025-05-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0007_postruangan_postuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostRuangan',
        ),
        migrations.RenameField(
            model_name='postuser',
            old_name='namaUser',
            new_name='Nama',
        ),
        #migrations.AddField(
        #    model_name='postuser',
        ##    name='NIP',
         #   field=models.CharField(blank=True, max_length=20, null=True),
        #),
        #migrations.AddField(
        #    model_name='postuser',
        #    name='Satker',
        #    field=models.CharField(blank=True, max_length=20, null=True),
        #),
    ]
