# Generated by Django 5.2.1 on 2025-05-27 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0008_delete_postruangan_rename_namauser_postuser_nama_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postuser',
            old_name='Nama',
            new_name='nama',
        ),
        ##migrations.RenameField(
         #   model_name='postuser',
         #   old_name='NIP',
         #  new_name='ruangan',
        #),
        #migrations.RenameField(
        #    model_name='postuser',
        #    old_name='Satker',
        #    new_name='satker',
        #),
        #migrations.AddField(
        ##    model_name='postdata',
          #  name='waktu',
          #  field=models.DateField(blank=True, null=True),
        #),
        #migrations.AddField(
        #    model_name='postuser',
        #    name='keterangan',
        #    field=models.TextField(blank=True, null=True),
        #),
        #migrations.AddField(
        #    model_name='postuser',
        #    name='waktu',
        #    field=models.DateField(blank=True, null=True),
        #),
        migrations.AlterField(
            model_name='postdata',
            name='nama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postuser'),
        )
    ]
