# Generated by Django 5.2.1 on 2025-05-27 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0009_rename_nama_postuser_nama_and_more'),
    ]

    operations = [
    #   migrations.RemoveField(
    #        model_name='postuser',
    #        name='keterangan',
    #    ),
    #    migrations.RemoveField(
    #        model_name='postuser',
    #       name='ruangan',
    #    ),
    #    migrations.RemoveField(
    #        model_name='postuser',
    #        name='waktu',
    #    ),
        migrations.AlterField(
           model_name='postdata',
            name='nama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postuser'),
        ),
    ]
