# Generated by Django 5.2.1 on 2025-05-27 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0011_postuser_nip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruangan', models.CharField(blank=True, max_length=25, null=True)),
                ('kapasitas', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostSatker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satker', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        #migrations.RemoveField(
        #    model_name='postuser',
        #    name='NIP',
        #),
        #migrations.AlterField(
        #    model_name='postdata',
        #    name='ruangan',
        #    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postruangan'),
        #),
        #migrations.AlterField(
        #    model_name='postdata',
        #    name='satker',
        #    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postsatker'),
        #),
    ]
