# Generated by Django 5.2.1 on 2025-05-27 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0012_postruangan_postsatker_remove_postuser_nip_and_more'),
    ]

    #operations = [
    #    migrations.RemoveField(
    #        model_name='postuser',
    #        name='satker',
    #    ),
    #]
