# Generated by Django 5.2.1 on 2025-05-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0015_remove_postuser_nip'),
    ]

    #operations = [
    #    migrations.AddField(
    #        model_name='postuser',
    #        name='NIP',
    #        field=models.CharField(blank=True, max_length=20, null=True),
    #    ),
    #]
