# Generated by Django 5.2.1 on 2025-05-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0016_postuser_nip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostUser',
            new_name='PostPeg',
        ),
    ]
