# Generated by Django 5.2.1 on 2025-05-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0017_rename_postuser_postpeg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostPeg',
            new_name='PostUser',
        ),
    ]
