# Generated by Django 5.2.1 on 2025-05-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0018_rename_postpeg_postuser'),
    ]

    #operations = [
    #    migrations.RemoveField(
    #        model_name='postuser',
    #        name='NIP',
    #    ),
    #]
