# Generated by Django 5.2.1 on 2025-05-27 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0020_alter_postdata_nama_alter_postdata_satker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='nama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postuser'),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='satker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postsatker'),
        ),
    ]
