# Generated by Django 5.2.1 on 2025-05-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0021_alter_postdata_nama_alter_postdata_satker'),
    ]

    operations = [
        migrations.AddField(
            model_name='postuser',
            name='NIP',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
