# Generated by Django 5.2.1 on 2025-05-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0022_postuser_nip'),
    ]

    #operations = [
    #    migrations.RemoveField(
    #        model_name='postuser',
    #        name='NIP',
    #    ),
    #]
