# Generated by Django 5.2.1 on 2025-05-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0024_alter_postdata_nama_alter_postdata_satker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='postdata',
            name='satker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postsatker'),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='nama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postuser'),
        ),
    ]
