# Generated by Django 5.2.1 on 2025-05-30 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0026_postuser_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='waktu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postuser',
            name='NIP',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='ruangan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postruangan'),
        ),
    ]
