# Generated by Django 5.2.1 on 2025-05-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0029_rename_nama_postdata_nama_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='id_data',
            field=models.BigIntegerField(default=True),
        ),
    ]
