# Generated by Django 5.2.1 on 2025-05-30 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0030_postdata_id_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='nama_id',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='postdata',
            name='id_data',
        ),
    ]
