# Generated by Django 5.2.1 on 2025-06-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0031_rename_nama_id_postdata_nama_remove_postdata_id_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='postuser',
            name='ruangan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postuser',
            name='satker',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
