# Generated by Django 5.2.1 on 2025-06-05 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0034_alter_postdata_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='nama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postuser'),
        ),
    ]
