# Generated by Django 5.2.1 on 2025-06-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0035_alter_postdata_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postruangan',
            name='kapasitas',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='postruangan',
            name='ruangan',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='postsatker',
            name='satker',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='nama',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='satker',
            field=models.CharField(max_length=50),
        ),
    ]
