# Generated by Django 5.2.1 on 2025-06-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0036_alter_postruangan_kapasitas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postuser',
            name='satker',
            field=models.CharField(max_length=25),
        ),
    ]
