# Generated by Django 5.2.1 on 2025-06-05 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0037_alter_postuser_satker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='nama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postuser'),
        ),
    ]
