# Generated by Django 5.2.1 on 2025-06-05 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0038_alter_postdata_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='ruangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postruangan'),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='satker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postsatker'),
        ),
    ]
