# Generated by Django 5.2.1 on 2025-06-05 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0039_alter_postdata_ruangan_alter_postdata_satker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='nama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postuser'),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='ruangan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postruangan'),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='satker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postsatker'),
        ),
    ]
