# Generated by Django 5.2.1 on 2025-06-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0040_alter_postdata_nama_alter_postdata_ruangan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postruangan',
            name='ruangan',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='postsatker',
            name='satker',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='nama',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='satker',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
