# Generated by Django 5.2.1 on 2025-06-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0041_alter_postruangan_ruangan_alter_postsatker_satker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postruangan',
            name='ruangan',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
