# Generated by Django 5.2.1 on 2025-06-08 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0042_alter_postruangan_ruangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='nama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postuser'),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='ruangan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postruangan'),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='satker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuUtama.postsatker'),
        ),
    ]
