# Generated by Django 5.2.1 on 2025-06-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0043_alter_postdata_nama_alter_postdata_ruangan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='keterangan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='waktu',
            field=models.DateField(),
        ),
    ]
