# Generated by Django 5.2.1 on 2025-06-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0045_postdata_pukul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='pukul',
            field=models.TimeField(verbose_name='Custom Field Time'),
        ),
    ]
