# Generated by Django 5.2.1 on 2025-06-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0047_remove_postdata_pukul'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='waktu',
            new_name='pukul',
        ),
        migrations.AddField(
            model_name='postdata',
            name='tanggal',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
