# Generated by Django 5.2.1 on 2025-06-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0049_alter_postdata_pukul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='pukul',
        ),
    ]
