# Generated by Django 5.2.1 on 2025-06-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0051_rename_tanggal_postdata_waktu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='waktu',
            new_name='tanggal',
        ),
        migrations.AddField(
            model_name='postdata',
            name='pukul',
            field=models.TimeField(default=0),
            preserve_default=False,
        ),
    ]
