# Generated by Django 5.2.1 on 2025-06-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0052_rename_waktu_postdata_tanggal_postdata_pukul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='pukul',
        ),
        migrations.RemoveField(
            model_name='postdata',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='postdata',
            name='waktu',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
