# Generated by Django 5.2.1 on 2025-06-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0054_alter_postdata_waktu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='waktu',
        ),
        migrations.AddField(
            model_name='postdata',
            name='pukul',
            field=models.TimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postdata',
            name='tanggal',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
