# Generated by Django 5.2.1 on 2025-06-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0055_remove_postdata_waktu_postdata_pukul_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='pukul',
        ),
        migrations.RemoveField(
            model_name='postdata',
            name='tanggal',
        ),
    ]
