# Generated by Django 5.2.1 on 2025-06-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0056_remove_postdata_pukul_remove_postdata_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='waktu',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
