# Generated by Django 5.2.1 on 2025-06-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0057_postdata_waktu'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='pukul',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
