# Generated by Django 5.2.1 on 2025-06-13 04:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0059_remove_postdata_pukul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='waktu',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
