# Generated by Django 5.2.1 on 2025-06-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuUtama', '0060_alter_postdata_waktu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='waktu',
            field=models.DateTimeField(),
        ),
    ]
