# Generated by Django 5.2.1 on 2025-05-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_data_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
