# Generated by Django 5.2.1 on 2025-05-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPinjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=200)),
                ('Satker', models.CharField(max_length=20)),
                ('Ruangan', models.CharField(max_length=200)),
                ('Waktu', models.DateTimeField(max_length=20)),
                ('Keterangan', models.TextField()),
            ],
        ),
    ]
