# Generated by Django 5.2.1 on 2025-05-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapinjam',
            name='Waktu',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
