# Generated by Django 5.2.1 on 2025-05-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_datapinjam_waktu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPinjam',
        ),
    ]
